name: tiffsy_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  lottie: ^2.7.0
  flutter_svg: ^2.0.8
  pinput: ^3.0.1
  bloc: ^8.1.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  google_sign_in: ^6.1.5
  equatable: ^2.0.5
  meta: ^1.9.1
  http: ^1.1.0
  cloud_firestore: ^4.13.6
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  table_calendar: ^3.0.9
  razorpay_flutter: ^1.3.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.4
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/ 
    - assets/
    - assets/images/vectors/
    - assets/images/vectors/address_book_screen/
    - assets/images/vectors/payment_checkout_screen/
    - assets/images/vectors/home_screen/
    - assets/images/vectors/cart_screen/
    - assets/loading_animations/
