// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Q5rZhDPGpa7obzcFp92RDrsv4N6qzWE',
    appId: '1:276683143717:web:363521db3541a273141dcc',
    messagingSenderId: '276683143717',
    projectId: 'tiffsy-foods',
    authDomain: 'tiffsy-foods.firebaseapp.com',
    storageBucket: 'tiffsy-foods.appspot.com',
    measurementId: 'G-NHWS75XEV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC49GEIdnhDXLWZUHgWG1b1Zsj3-I2TPdM',
    appId: '1:276683143717:android:998f845e1a4ce7a9141dcc',
    messagingSenderId: '276683143717',
    projectId: 'tiffsy-foods',
    storageBucket: 'tiffsy-foods.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkOVVPHP4s2dw-FKpVJMfm38aGCgKnxSs',
    appId: '1:276683143717:ios:cc78be58b8c78779141dcc',
    messagingSenderId: '276683143717',
    projectId: 'tiffsy-foods',
    storageBucket: 'tiffsy-foods.appspot.com',
    androidClientId: '276683143717-7090m9n00is1rknfn25in3rtqs8gfq3h.apps.googleusercontent.com',
    iosClientId: '276683143717-fng25r09u5u9h0jnp9j092iio9i4d0p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiffsyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkOVVPHP4s2dw-FKpVJMfm38aGCgKnxSs',
    appId: '1:276683143717:ios:3a57fcfb4373920f141dcc',
    messagingSenderId: '276683143717',
    projectId: 'tiffsy-foods',
    storageBucket: 'tiffsy-foods.appspot.com',
    androidClientId: '276683143717-7090m9n00is1rknfn25in3rtqs8gfq3h.apps.googleusercontent.com',
    iosClientId: '276683143717-k504mfvdglnee327p8u5dfa2bma7efk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiffsyApp.RunnerTests',
  );
}
